# Generated by Django 4.0.4 on 2022-06-14 04:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_address_apto_alter_address_corner_or_ave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apto',
            field=models.CharField(max_length=100, verbose_name='No. Y/O APTO'),
        ),
        migrations.AlterField(
            model_name='address',
            name='corner_or_ave',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='municipality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='militant',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
        migrations.AlterField(
            model_name='militant',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 4, 25, 55, 234138)),
        ),
    ]
