# Generated by Django 4.0.4 on 2022-06-15 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_militant_sex_militant_status_alter_core_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militant',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 23, 39, 6, 479349)),
        ),
        migrations.AlterField(
            model_name='militant',
            name='sex',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='militant',
            name='status',
            field=models.CharField(choices=[('Casado/a', 'Casado/A'), ('Soltero/a', 'Soltero/A'), ('Divorciado/a', 'Divorciado/A')], max_length=20, null=True),
        ),
    ]
