# Generated by Django 4.0.4 on 2022-06-16 03:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_militant_ci_alter_militant_first_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdeclaration',
            old_name='payment_norm',
            new_name='norm',
        ),
        migrations.AlterField(
            model_name='militant',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 3, 45, 24, 259254)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.paymentdeclaration'),
        ),
    ]
